Added fuzz for rockdb implementation for ledger

diff --git a/.github/workflows/check.yml b/.github/workflows/check.yml
--- a/.github/workflows/check.yml
+++ b/.github/workflows/check.yml
@@ -55,7 +55,7 @@ jobs:
 
       - name: test
         run: |
-          zig build test -Denable-tsan=true 
+          zig build test -Denable-tsan=true
           zig build test -Denable-tsan=true -Dblockstore=hashmap -Dfilter=ledger
 
   kcov_test:
@@ -80,6 +80,12 @@ jobs:
         run: |
           wget https://github.com/SimonKagstrom/kcov/releases/download/v42/kcov-amd64.tar.gz
           sudo tar xf kcov-amd64.tar.gz -C /
+      
+      - name: fix kcov dependencies
+        run: |
+          cd /usr/lib/x86_64-linux-gnu/
+          sudo ln libopcodes-2.42-system.so libopcodes-2.38-system.so || echo libopcodes not found
+          sudo ln libbfd-2.42-system.so libbfd-2.38-system.so || echo libbfd not found
 
       - name: run kcov
         run: |
@@ -170,90 +176,90 @@ jobs:
       - name: run
         run: ./zig-out/bin/fuzz allocators 19 10000
 
-  benchmarks:
-    if: ${{ github.ref != 'refs/heads/main' }}
-    strategy:
-      matrix:
-        os: [ubuntu-latest]
-    runs-on: ${{matrix.os}}
-    timeout-minutes: 60
-    steps:
-      - name: checkout
-        uses: actions/checkout@v2
-        with:
-          submodules: recursive
-      - name: setup zig
-        uses: mlugg/setup-zig@v1
-        with:
-          version: 0.13.0
-      - name: benchmarks
-        run: zig build -Doptimize=ReleaseSafe benchmark -- all --metrics
+  # benchmarks:
+  #   if: ${{ github.ref != 'refs/heads/main' }}
+  #   strategy:
+  #     matrix:
+  #       os: [ubuntu-latest]
+  #   runs-on: ${{matrix.os}}
+  #   timeout-minutes: 60
+  #   steps:
+  #     - name: checkout
+  #       uses: actions/checkout@v2
+  #       with:
+  #         submodules: recursive
+  #     - name: setup zig
+  #       uses: mlugg/setup-zig@v1
+  #       with:
+  #         version: 0.13.0
+  #     - name: benchmarks
+  #       run: zig build -Doptimize=ReleaseSafe benchmark -- all --metrics
 
-      # Download previous benchmark result from cache (if exists)
-      - name: Download previous benchmark data
-        uses: actions/cache@v4
-        with:
-          path: ./cache
-          key: ${{ runner.os }}-benchmark
+  #     # Download previous benchmark result from cache (if exists)
+  #     - name: Download previous benchmark data
+  #       uses: actions/cache@v4
+  #       with:
+  #         path: ./cache
+  #         key: ${{ runner.os }}-benchmark
 
-      # Run `github-action-benchmark` action
-      - name: Store benchmark result
-        uses: benchmark-action/github-action-benchmark@v1
-        with:
-          # What benchmark tool the output.txt came from
-          tool: "customSmallerIsBetter"
-          # Where the output from the benchmark tool is stored
-          output-file-path: results/output.json
-          # Where the previous data file is stored
-          external-data-json-path: ./cache/benchmark-data.json
-          # Workflow will fail when an alert happens
-          fail-on-alert: true
-          # GitHub API token to make a commit comment
-          github-token: ${{ secrets.GITHUB_TOKEN }}
-          # Enable alert commit comment
-          comment-on-alert: true
-          # Upload the updated cache file for the next job by actions/cache
-          # only when running on the main branch
-          save-data-file: false
+  #     # Run `github-action-benchmark` action
+  #     - name: Store benchmark result
+  #       uses: benchmark-action/github-action-benchmark@v1
+  #       with:
+  #         # What benchmark tool the output.txt came from
+  #         tool: "customSmallerIsBetter"
+  #         # Where the output from the benchmark tool is stored
+  #         output-file-path: results/output.json
+  #         # Where the previous data file is stored
+  #         external-data-json-path: ./cache/benchmark-data.json
+  #         # Workflow will fail when an alert happens
+  #         fail-on-alert: true
+  #         # GitHub API token to make a commit comment
+  #         github-token: ${{ secrets.GITHUB_TOKEN }}
+  #         # Enable alert commit comment
+  #         comment-on-alert: true
+  #         # Upload the updated cache file for the next job by actions/cache
+  #         # only when running on the main branch
+  #         save-data-file: false
 
-  main_benchmarks:
-    if: ${{ github.ref == 'refs/heads/main' }}
-    strategy:
-      matrix:
-        os: [ubuntu-latest]
-    runs-on: ${{matrix.os}}
-    timeout-minutes: 60
-    steps:
-      - name: checkout
-        uses: actions/checkout@v2
-        with:
-          submodules: recursive
-      - name: setup zig
-        uses: mlugg/setup-zig@v1
-        with:
-          version: 0.13.0
-      - name: benchmarks
-        run: zig build -Doptimize=ReleaseSafe benchmark -- all --metrics
+  # main_benchmarks:
+  #   if: ${{ github.ref == 'refs/heads/main' }}
+  #   strategy:
+  #     matrix:
+  #       os: [ubuntu-latest]
+  #   runs-on: ${{matrix.os}}
+  #   timeout-minutes: 60
+  #   steps:
+  #     - name: checkout
+  #       uses: actions/checkout@v2
+  #       with:
+  #         submodules: recursive
+  #     - name: setup zig
+  #       uses: mlugg/setup-zig@v1
+  #       with:
+  #         version: 0.13.0
+  #     - name: benchmarks
+  #       run: zig build -Doptimize=ReleaseSafe benchmark -- all --metrics
 
-      # Download previous benchmark result from cache (if exists)
-      - name: Download previous benchmark data
-        uses: actions/cache@v4
-        with:
-          path: ./cache
-          key: ${{ runner.os }}-benchmark
+  #     # Download previous benchmark result from cache (if exists)
+  #     - name: Download previous benchmark data
+  #       uses: actions/cache@v4
+  #       with:
+  #         path: ./cache
+  #         key: ${{ runner.os }}-benchmark
 
-      # Run `github-action-benchmark` action
-      - name: Store benchmark result
-        uses: benchmark-action/github-action-benchmark@v1
-        with:
-          # What benchmark tool the output.txt came from
-          tool: "customSmallerIsBetter"
-          # Where the output from the benchmark tool is stored
-          output-file-path: results/output.json
-          # Where the previous data file is stored
-          external-data-json-path: ./cache/benchmark-data.json
-          # Workflow will fail when an alert happens
-          fail-on-alert: true
-          # Upload the updated cache file for the next job by actions/cache
-          # only when running on the main branch (see if:)
-          save-data-file: true
+  #     # Run `github-action-benchmark` action
+  #     - name: Store benchmark result
+  #       uses: benchmark-action/github-action-benchmark@v1
+  #       with:
+  #         # What benchmark tool the output.txt came from
+  #         tool: "customSmallerIsBetter"
+  #         # Where the output from the benchmark tool is stored
+  #         output-file-path: results/output.json
+  #         # Where the previous data file is stored
+  #         external-data-json-path: ./cache/benchmark-data.json
+  #         # Workflow will fail when an alert happens
+  #         fail-on-alert: true
+  #         # Upload the updated cache file for the next job by actions/cache
+  #         # only when running on the main branch (see if:)
+  #         save-data-file: true
